git-license-parser:
  kafka:
    consumer-enabled: ${consumer-enabled:true}
spring:
  data:
    mongodb:
      host: ${mongo-host:localhost}
      port: 27017
      database: ${mongo-database:mongo}
  kafka:
    bootstrap-servers: ${kafka_bootstrap_servers:192.168.88.73:9093}
    properties:
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
        mechanism: PLAIN
      security:
        protocol: PLAINTEXT
    consumer:
      auto-offset-reset: earliest
      group-id: git-license-parser
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 1
      fetch-max-wait: 3600
      enable-auto-commit: false
      client-id: git-license-parser
    jaas:
      enabled: true
    listener:
      poll-timeout: 1800000
      concurrency: 1
      ack-mode: manual_immediate